# Generated by Django 5.2.3 on 2025-06-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at_alter_docs_user_alter_user_phone_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docs',
            new_name='Document',
        ),
    ]
