# Generated by Django 5.2.3 on 2025-06-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniyathalaimurai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
