# Generated by Django 5.2.3 on 2025-06-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iniyathalaimurai', '0002_servicecategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='application',
            name='userPaymentStatus',
        ),
    ]
