# Generated by Django 5.2.3 on 2025-06-20 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniyathalaimurai', '0003_remove_application_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicationAppliedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='iniyathalaimurai.service'),
        ),
    ]
