# Generated by Django 5.2.3 on 2025-06-20 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniyathalaimurai', '0004_alter_application_applicationappliedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iniyathalaimurai.service'),
        ),
    ]
