# Generated by Django 5.2.3 on 2025-06-22 08:26

import django.db.models.deletion
import iniyathalaimurai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniyathalaimurai', '0006_application_applicationid_payment_paymentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to='payment_screenshots/', validators=[iniyathalaimurai.models.validate_filetype]),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
        migrations.CreateModel(
            name='SubmittedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submitted_documents/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='iniyathalaimurai.application')),
            ],
        ),
    ]
