# Generated by Django 5.2.3 on 2025-06-22 12:03

import iniyathalaimurai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniyathalaimurai', '0007_payment_screenshot_service_price_submitteddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitteddocument',
            name='file',
            field=models.FileField(upload_to='submitted_documents/', validators=[iniyathalaimurai.models.validate_filetype]),
        ),
    ]
