# Generated by Django 5.2.3 on 2025-06-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniyathalaimurai', '0008_alter_submitteddocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='acknowledgementNumber',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicationAppliedAt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('verifying', 'Verifying'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='verifying', max_length=20),
        ),
    ]
