# Generated by Django 5.2.3 on 2025-06-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iniyathalaimurai', '0009_application_acknowledgementnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paymentID',
            new_name='transactionID',
        ),
    ]
