# Generated by Django 5.2.3 on 2025-06-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniyathalaimurai', '0010_rename_paymentid_payment_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicationAppliedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
