# Generated by Django 5.2.3 on 2025-06-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniyathalaimurai', '0011_alter_application_applicationappliedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicationAppliedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
